name: Deploy Cloud Function

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
  REGION: ${{ secrets.REGION }}
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Deploy Function
        run: |
          # Build the container
          gcloud builds submit \
            --config=function/Dockerfile \
            --tag=gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.FUNCTION_NAME }} \
            function/

          # Deploy the function
          gcloud functions deploy ${{ secrets.FUNCTION_NAME }} \
            --gen2 \
            --runtime=python39 \
            --region=${{ secrets.REGION }} \
            --source=function \
            --trigger-http \
            --allow-unauthenticated \
            --set-env-vars=GCS_BUCKET=${{ secrets.GCS_BUCKET }} \
            --docker-registry=artifact-registry \
            --docker-repository=functions \
            --dockerfile=Dockerfile
